/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData user = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address = const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_2 = const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_3 = const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData find = const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_2 = const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_3 = const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_stay = const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bathroom = const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed = const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler = const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ac = const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chair = const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData door_man = const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heater = const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gym = const IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData balcony = const IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cctv = const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parking = const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pool = const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_pets = const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pet = const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi = const IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_drugs = const IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_drinking = const IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData elevator = const IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_smoking = const IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
